import type { Metadata } from "next";
import { Inter } from "next/font/google";

import Footer from "@/components/footer";
import "./globals.css";
import Header from '@/components/header'
import {unstable_setRequestLocale} from 'next-intl/server';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const locales = ['en', 'ru'];
 
export function generateStaticParams() {
  return locales.map((locale) => ({locale}));
}

interface RootLayoutProps{
  children: React.ReactNode;
  params:{
    locale:string;
  }
}
export default function LocaleLayout({
  children,
  params:{locale}
}: Readonly<RootLayoutProps>) {
  unstable_setRequestLocale(locale);

  return (
    <html lang={locale}>
      <body className={inter.className}>
        
        <Header params={{locale}}/>
        {children}
        <Footer />
        </body>
    </html>
  );
}
